# Front UI dockerfile
FROM node:21-alpine

WORKDIR /usr/src/app
# Copy package.json, package-lock.json, Next.js, Tailwind CSS configuration files
COPY package.json package-lock.json ./
COPY configs/next.config.js ./
COPY configs/postcss.config.js ./
COPY configs/tailwind.config.js ./

RUN npm install

COPY . .

RUN npm run build


EXPOSE 3000


# switch back to this if run dev
#CMD ["npm", "start"]
CMD ["npm", "run", "dev"]


