version: '3'

# This container includes 5 services - application-server, application-ui, mongo, mongo-express. and grafana
services: 
  kafka-kare-server: 
    image: kafka-kare-server 
    ports: 
      - "3001:3001"
    depends_on:
      - mongo
    environment:
     - MONGO_DB_USERNAME=admin # Same username and password. MUST MATCH. 
     - MONGO_DB_PWD=supersecret
    networks:
     - kafka-kare-network

  kafka-kare-ui:
    image: kafka-kare-ui
    ports:
     - 3000:3000 #Frontend on localhost:3000
    depends_on:
     - kafka-kare-server
    networks:
     - kafka-kare
    develop:
     watch:
        - action: sync
          path: ./
          target: /
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json   
  #does not work if you change name from mongo 
  mongo:
    image: mongo
    ports:
     - 27017:27017
    environment: 
     - MONGO_INITDB_ROOT_USERNAME=admin # Same username and password. MUST MATCH. 
     - MONGO_INITDB_ROOT_PASSWORD=supersecret
    networks:
      - kafka-kare-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin # Same username and password. MUST MATCH. 
     - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
     - ME_CONFIG_MONGODB_URL=mongodb://admin:supersecret@mongo
     #new way is to use mongo URL
    #  - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
     - kafka-kare-network
    depends_on:
      - mongo

  grafana: 
    image: grafana/grafana:latest
    ports: 
      - "3002:3000" # running on localhost:3002
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "kafkakarepw" #username is admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
     - kafka-kare-server
    networks:
     - kafka-kare-network
networks: 
  kafka-kare-network:
    driver: bridge
volumes:
  mongo-data: 
  grafana-data: