FROM node:21-alpine

WORKDIR /app/server
COPY package*.json ./
COPY . .
RUN npm install
EXPOSE 3001
#will start server in dev mode with nodemon. Not recommended for production
CMD [ "npm","run", "server" ]