version: '3'
services: 
  kafka-kare-server: 
    image: kafka-kare-test
    ports: 
      - "3001:3001"
    depends_on:
      - mongo
    environment:
     - MONGO_DB_USERNAME=admin
     - MONGO_DB_PWD=supersecret
    networks:
     - kafka-kare
  kafka-kare-ui:
    image: kafka-kare-ui1
    ports:
     - 3000:3000
    depends_on:
     - kafka-kare-server
    networks:
     - kafka-kare    
  #does not work if you change name from mongo 
  mongo:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=supersecret
    networks:
      - kafka-kare
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
     - ME_CONFIG_MONGODB_URL=mongodb://admin:supersecret@mongo
     #new way is to use mongo URL
    #  - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
     - kafka-kare
    depends_on:
     - "mongo"
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=http://localhost:3002
    #  - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3002:3002'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    depends_on:
     - kafka-kare-ui
    networks:
     - kafka-kare  
networks: 
  kafka-kare:
    driver: bridge
volumes:
  mongo-data: 
  grafana_storage: {}