version: '3.8'

# This container includes 5 services - application-server, application-ui, mongo, mongo-express. and grafana
services: 
  kafka-kare-server: 
    build: 
      context: .
      dockerfile: Dockerfile-server    
    ports: 
      - "3001:3001"
      #for hot reloading in server, not working now
    # volumes:
    #   - ./server:/app/server
    #   - /app/node_modules
    #overides CMD in Dockerfile-server. This will start the server in dev mode(using nodemon)   
    command: npm run prod
    #npm run server        
    depends_on:
      - mongo
    environment:
     - MONGO_DB_USERNAME=admin # Same username and password. MUST MATCH. 
     - MONGO_DB_PWD=supersecret
    networks:
     - kafka-kare-network
    # develop:
    #  watch:
    #     # - path: ./server/server.js
    #     #   target: /app/server
    #     #   action: sync
    #     - path: /package.json
    #       action: rebuild
  kafka-kare-ui:
    build: 
      context: .
      dockerfile: Dockerfile-ui
    ports:
     - 3000:3000 #Frontend on localhost:3000
    depends_on:
     - kafka-kare-server
    networks:
     - kafka-kare-network
    #volumes are necessary for hot reloading
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # watch isn't working perfectly. Need to figure out how to sync files correctly. So hot reloading in dev mode works.
    # develop:
    #   watch:
    #     - path: ./app/package.json
    #       action: rebuild
    #     - path: ./app/src/components
    #       target: /usr/src/app
    #       action: sync
  #does not work if you change name from mongo 
  mongo:
    image: mongo
    ports:
     - 27017:27017
    environment: 
     - MONGO_INITDB_ROOT_USERNAME=admin # Same username and password. MUST MATCH. 
     - MONGO_INITDB_ROOT_PASSWORD=supersecret
    networks:
      - kafka-kare-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin # Same username and password. MUST MATCH. 
     - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
     - ME_CONFIG_MONGODB_URL=mongodb://admin:supersecret@mongo
     #new way is to use mongo URL
    #  - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
     - kafka-kare-network
    depends_on:
      - mongo

  grafana: 
    image: grafana/grafana:latest
    ports: 
      - "3002:3000" # running on localhost:3002
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "kafkakarepw" #username is admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources #needed for provisioning
    depends_on:
     - kafka-kare-server
    networks:
     - kafka-kare-network
networks: 
  kafka-kare-network:
    driver: bridge
volumes:
  mongo-data: 
  grafana-data: