version: '3.8'
services: 
  kafka-kare-server: 
    image: kafka-kare-server4
    ports: 
      - "3001:3001"
    networks: 
      - kafka-kare
    # Use either environment OR env_file. Environment for testing/development. 
    # Also change server.js file to match literal URI versus env_file
    # The MONGO_URI is based off the username and password. env_file for production as more secure
    environment:
      - MONGO_URI=mongodb://KafkaKare:sHRtyVkFa7aOykcX@mongo:27017/kafka-kare?authSource=admin
    # env_file:
    #   - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    # Use either environment OR env_file. Environment for testing/development
    environment:
      MONGO_INITDB_ROOT_USERNAME: KafkaKare
      MONGO_INITDB_ROOT_PASSWORD: sHRtyVkFa7aOykcX
    # env_file:
    #   - .env
    ports:
      - "27017:27017"
    networks:
      - kafka-kare
    volumes:
      - mongo-data:/data/db
networks: 
  kafka-kare:
    driver: bridge
volumes:
  mongo-data: 