version: '3'
services: 
  kafka-kare-server: 
    image: kafka-kare-server
    ports: 
      - "3001:3001"
    depends_on:
      - mongo
    # Provides the application container with the same username and password. MUST MATCH. 
    environment:
     - MONGO_DB_USERNAME=admin
     - MONGO_DB_PWD=supersecret
    networks:
     - kafka-kare-network
  kafka-kare-ui:
    image: kafka-kare-ui
    ports:
     - 3000:3000
    depends_on:
     - kafka-kare-server
    networks:
     - kafka-kare-network
  #does not work if you change name from mongo 
  mongo:
    image: mongo
    ports:
     - 27017:27017
    # Configures the MongoDB container with the same username and password. MUST MATCH. 
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=supersecret
    networks:
      - kafka-kare-network
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=supersecret
     - ME_CONFIG_MONGODB_URL=mongodb://admin:supersecret@mongo
     #new way is to use mongo URL
    #  - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
     - kafka-kare-network
    depends_on:
     - "mongo"
  grafana: 
    image: grafana/grafana:latest
    ports: 
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "kafkakarepw"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - kafka-kare-server
    networks:
      - kafka-kare-network
networks: 
  kafka-kare-network:
    driver: bridge

volumes:
  mongo-data: 
  grafana-data: