global:
  scrape_interval: 15s

scrape_configs: 
  - job_name: 'kafka-kare'
  static_configs: 
    - targets: ['kafka-kare-server:3001']

  - job_name: 'kafka-demo'
  static_configs: 
    - targets: ['kafka-demo:9092']