{
 "title": "Kafka Kare Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Log Segment Size By Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka\"}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_replicationbytesin_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": " sum(kafka_server_replicamanager_partitioncount{job=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_metadataerrorcount\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Broker Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node-exporter\",mountpoint=\"/kafka\"}) - sum(node_filesystem_free_bytes{job=\"node-exporter\",mountpoint=\"/kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used", "legendFormat": "__auto" },
    { "expr": "jvm_memory_pool_bytes_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Latency By Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\"}[5m])) by (topic))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Process in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Messages Consumed Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(kafka_server_consumerfetchmanager_metrics_records_consumed_total{job=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages Produced Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under-Replicated Partitions Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_cluster_partition_underreplicated",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "kafka_server_fetcherlagmetrics_consumerlag",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failed Fetch Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedfetchrequests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Groups Rebalancing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "kafka_coordinator_group_groupmetadatamanager_numgroupscompletingrebalance",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}