# Configuration file specifying how Prometheus should scrape metrics
global:
  scrape_interval: 1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: 'kafka' # Scrape job for Kafka
    scheme: http
    static_configs:
      - targets: ['kafka:7070'] # Pointing to the target Port 7070, which is the port exposed by the JMX Exporter